### ISSUE TITLE
GabutDM make /home/user/Downloads in selected folder in Settings

### ISSUE THREAD

**Issue by Anifyuli** [gabutakut/gabutdm#218]
Hello, Mister. 

I find a mistake or bug in your app. GabutDM make /home/user/Downloads in Downloads system directory. I change it in new folder but GabutDM make this bug appear again. You can get my point after see this screenshots.

After make new directory
![Screenshot from 2023-01-23 17-29-18](https://user-images.githubusercontent.com/73734843/214018363-572e8e3b-4150-4df1-9de0-cd73a1c1b5da.png)
Saved files locations
![Screenshot from 2023-01-23 17-29-38](https://user-images.githubusercontent.com/73734843/214018355-d7b13482-25f1-45d1-af6e-ad4daf3c62a1.png)

Thanks for read my issues.

**Comment by githubuser013** [comment]
For me too.

**Comment by abraham-sah** [comment]
Same problem happens here, with Mainline Arch with `flatpak 1:1.15.4-1` and `com.github.gabutakut.gabutdm 2.1.6` on `gnome-shell 1:44.4-1.1`.

It only happens when it starts a new download with interrupting the browser's download. But not when it starts a new download from clipboard.
Current workaround is to remove the `filename:` text-box each time.

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutextentionsFF/pull/18
